site_name: Collaborative State Machines (CSM)
repo_url: https://github.com/CollaborativeStateMachines/Cirrina
site_url: https://collaborativestatemachines.github.io/
theme:
  name: shadcn
  custom_dir: overrides
  show_title: true
  show_stargazers: true
  pygments_style: 
        light: shadcn-light
        dark: github-dark
  icon: https://collaborativestatemachines.github.io/assets/cirrina/icon.svg
  favicon: https://collaborativestatemachines.github.io/assets/cirrina/icon.svg
  topbar_sections: true
  show_datetime: true 
plugins:
  - autorefs
  - awesome-nav
  - bibtex:
      bib_file: "refs.bib"
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - fenced_code
  - footnotes
  - pymdownx.blocks.caption
  - shadcn.extensions.iconify